title: Wiki Atald
description: Le serveur minecraft Atald !
remote_theme: just-the-docs/just-the-docs
url: https://senssiii.github.io

search_enabled: true

just_the_docs:
  custom_css:
    - "assets/css/custom.css"