title: Wiki Atald
description: Documentation du serveur Minecraft RP
theme: just-the-docs
url: https://senssiii.github.io

# Active la recherche (optionnel)
search_enabled: true
just-the-docs:
  custom-css:
    - "assets/css/custom.css"