title: Wiki Atald
description: Documentation du serveur Minecraft RP
theme: just-the-docs
url: https://senssiii.github.io

# Active la recherche (optionnel)
search_enabled: true

# Navigation personnalisée
nav:
  - title: Virmian
    url: /Virmian_base.html
    children:
      - title: Domaine Royal
        url: /domaine_royal.html

just_the_docs:
  custom_css:
    - "assets/css/custom.css" # ou utilise juste _sass/custom/custom.scss
