title: Wiki Atald
description: Documentation du serveur Minecraft RP
theme: just-the-docs
url: https://senssiii.github.io

# Active la recherche (optionnel)
search_enabled: true

# Pour que le layout personnalisé soit utilisé
defaults:
  - scope:
      path: "regles.md"
    values:
      layout: regles


just_the_docs:
  custom_css:
    - "assets/css/custom.css" # ou utilise juste _sass/custom/custom.scss
