title: Wiki Atald
description: Documentation du serveur Minecraft RP
theme: just-the-docs
url: https://senssiii.github.io

# Active la recherche (optionnel)
search_enabled: true
just_the_docs:
  custom_css:
    - "assets/css/custom.css"