site_name: Les Archives de Karak
theme:
  name: material
  favicon: assets/logo_karak.png
  font:
    text: Marcellus       # Une police élégante d'inspiration antique/médiévale
    code: Roboto Mono
  palette:
    # OPTION 1 : Mode Parchemin / Érudit (Clair)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: brown       # Couleur des menus (effet cuir / terre)
      accent: amber        # Couleur des liens et détails (effet or / bougie)
      toggle:
        icon: material/candle
        name: Passer au mode nuit

plugins:
  - search

nav:
  - Accueil: index.md
  - Léos: royaumes/leos.md
  - Religion:
    - Varunat: religion/varunat.md
    - Serathisme: religion/serathisme.md
use_directory_urls: false
